### ISSUE TITLE
upgrade from 1.7.3.0 to 1.7.4.1

### ISSUE THREAD

**Issue by wewew85** [PrestaShop/autoupgrade#112]
Hi, I am trying to update from 1.7.3.0 to 1.7.4.1 with your module but it is not working. Version comparison is still loading. I also tried manual upgrade and the result is not working. After click on save button nothing happend. 
![image](https://user-images.githubusercontent.com/41673053/43199971-10e7dc42-9014-11e8-9f0a-acfe9d689c69.png)

cold you pls hepl me. thx

**Comment by Quetzacoalt91** [comment]
Hello, this is most likely caused by an error 500 on the different pre-upgrade checks.

We cannot know how to fix issue until you give us more details. Please open the console of your browser and checks the ajax requests made when you open the configuration page.

In the content returned by the server, you will have the error messages displayed.
For instance on Firefox:
![capture du 2018-07-25 14-27-19](https://user-images.githubusercontent.com/6768917/43200845-1bc2af22-9017-11e8-9442-3b98160eee8d.png)

Look for a request with a code 500 written, not 200.

**Comment by V41F** [comment]
thx for you response. When I open the configuration page there is no ajax requests. 
![image](https://user-images.githubusercontent.com/41673053/43201633-56c6caa2-9019-11e8-9ad2-f387f76c84dd.png)

**Comment by PierreRambaud** [comment]
Hi,

You're using Chrome, you have an `XHR` (For Xml Http Request) button on the top right, if you click on it you will be able to see every ajax requests ;)

Regards

**Comment by V41F** [comment]
Hi, no I am using firefox exactly like your screenshot
![image](https://user-images.githubusercontent.com/41673053/43202773-a956ca30-901c-11e8-9fd8-4a6b3a361d2e.png)

**Comment by V41F** [comment]
here you can see (no ajax requests)
![image](https://user-images.githubusercontent.com/41673053/43203362-4c2024e0-901e-11e8-934b-95b6392fb38a.png)

**Comment by PierreRambaud** [comment]
Do you have something in your  `Console` tab?

**Comment by V41F** [comment]
what do you mean exactly?

web console:
![image](https://user-images.githubusercontent.com/41673053/43213553-333e7440-9037-11e8-9194-5cb518b1254f.png)

browser console:
![image](https://user-images.githubusercontent.com/41673053/43213656-71ac795c-9037-11e8-8bc1-67f22d00111a.png)

**Comment by PierreRambaud** [comment]
It's just in case you could have some exceptions and especially to identify why your xhr is empty :/ Do you open your tab after or before running the autoupgrade? If it's before, look like notification_17.js script  break the javascript execution :/

**Comment by V41F** [comment]
before. If I click on autoupgrade prestashop, nothing happened. only scroll up on the top of page. why is version comparison still loading without any result? what about permission?

**Comment by PierreRambaud** [comment]
So, look like there is a bug with file notification_17.js, that break the javascript execution. Where this file come from? :)

**Comment by V41F** [comment]
it is from GDPR module. Should I block the module and try it or need to be unistall?

**Comment by PierreRambaud** [comment]
Yes, could be a good idea to do that. :) Waiting for your feedback.

**Comment by V41F** [comment]
so I unistall the module and I tried to upgrade. Now I have no access to BO and also front office  is down. Internal server error...
![image](https://user-images.githubusercontent.com/41673053/43256346-b6b30d32-90cc-11e8-9c5d-04b00e33ec86.png)

so thanks a lot, problem was the module. But now I have bigger problem:-((

**Comment by PierreRambaud** [comment]
If it's what I think and you installed the 1.7.4.1, you need to edit your .htaccess files and change  `Order allow, deny` to `Order allow,deny` (Note the space). We will release very soon the 1.7.4.2 (maybe  in few hours) :)

**Comment by PierreRambaud** [comment]
And more, can you tell me with GDPR module did you download? Is it the PrestaShop one?

**Comment by V41F** [comment]
I was farsighted and I made backup. So now it is OK and I will wait for release 1.7.4.2 and after that I will do it again and hope with happy end:-) thanks a lot for your help. I appreciate it!

GDPR module is not Prestashop. I will write massage to them, if they can set up right:-)
thx.

**Comment by PierreRambaud** [comment]
Nice! We will close this issues after you will upgrade to 1.7.4.2 to be sure everything is ok for you ;)

**Comment by Quetzacoalt91** [comment]
FYI @wewew85, PS 1.7.4.2 has been released last week, you can try another upgrade. :)

**Comment by V41F** [comment]
Hello @Quetzacoalt91 , yes I tried to upgrade on PS 1.7.4.2 but with this result:

[Ajax / Server Error for action upgradeFiles] textStatus: "error " errorThrown:"Internal Server Error " jqXHR: "

what is wrong?
thx

**Comment by khouloudbelguith** [comment]
Hi @wewew85 

What is the exact version of the 1-click upgrade module did you used?

Best regards, Khouloud

**Comment by V41F** [comment]
Hi @khouloudbelguith I used v4.0.0.

**Comment by Quetzacoalt91** [comment]
We can't do anything with the log `[Ajax / Server Error for action upgradeFiles] textStatus: "error " errorThrown:"Internal Server Error " jqXHR: "`.

However, the file `<admin folder>/autoupgrade/tmp/log.txt` should bring us more details. Can you please have a look at it?

**Comment by V41F** [comment]
OK, but I have to try to upgrade again and copy log.txt because I already upload my backup because my e-shop was unavailable.

**Comment by V41F** [comment]
I have it. What exactly you need to know?

**Comment by Quetzacoalt91** [comment]
It contains all the log outputted during the upgrade, you should find in it the error thrown during the process.

**Comment by V41F** [comment]
Sorry, but there is no error. Last message in log file is:
[2018-08-09 16:18:03] 19112 files left to upgrade.

**Comment by Quetzacoalt91** [comment]
Is that all? Nothing with the tag `[ INTERNAL ]`? I'm afraid without more details we won't be able to provide further help. :/

**Comment by V41F** [comment]
I found only this:
[2018-08-09 16:15:06] [INTERNAL] /var/www/hosting/tvojefarma.cz/modules/autoupgrade/classes/UpgradeTools/FilesystemAdapter.php line 94 - is_link(): open_basedir restriction in effect. File(/var/www/hosting/tvojefarma.cz/..) is not within the allowed path(s): (/var/www/hosting/tvojefarma.cz:/tmp)

**Comment by Quetzacoalt91** [comment]
Would you mind attaching the whole log file?

**Comment by PierreRambaud** [comment]
Look like it's an `open_basedir` restriction. We maybe need to use a different `/tmp` directory, such as `var/tmp`?

**Comment by V41F** [comment]
I don't know if it's good idea because then it's public and everyone can see the name of admin folder...

**Comment by Quetzacoalt91** [comment]
Well, the `is_link()` is used in the step "BackupFiles", and the script seem to fail during "UpgradeFiles". This is not the actual issue.

It could be a memory allocation exception, as @eternoendless reported, or an execution time issue.
@wewew85, it would be great to check your `max_execution_time` and `memory_limit` values.

**Comment by V41F** [comment]
OK, sorry but where I can find this values?

**Comment by Quetzacoalt91** [comment]
Okay, we can check you're not reaching the execution time limit. When you run the upgrade, check your browser console, again in with XHR filter:
![image](https://user-images.githubusercontent.com/41673053/43202773-a956ca30-901c-11e8-9fd8-4a6b3a361d2e.png)

If one of the calls lasts 30 seconds and ends with an return code 500 or with an empty response, this could be the issue. The "timings" tab will give you the information needed.

In the meantime we will work on our side with the error you reported about the open_basedir restriction.

**Comment by PierreRambaud** [comment]
Hi @wewew85 
We really can't do anything without the whole log file, these errors are too generic. 
If you prefer and you don't know how to substitute your admin directory in the log, you can send us an -mail at pierre.rambaud@prestashop.com
Thanks

**Comment by PierreRambaud** [comment]
@wewew85 @Quetzacoalt91 still waiting information to continue the investigation :)

**Comment by V41F** [comment]
Hi @Quetzacoalt91 
so I tried to upgrade and here is the result. really frustrating:-(
![snimek obrazovky 2018-09-11 v 21 43 44](https://user-images.githubusercontent.com/41673053/45386483-bd380880-b613-11e8-8df4-6e79e99bc0b1.png)

**Comment by Quetzacoalt91** [comment]
@wewew85, please open the `ajax-upgradetab.php` line with the `500` , and look at the response content. You should see what's actually wrong during the shop. :)

**Comment by V41F** [comment]
@Quetzacoalt91 I have no idea what is wrong:
<?php

/**
 * 2007-2016 PrestaShop.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@prestashop.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
 * versions in the future. If you wish to customize PrestaShop for your
 * needs please refer to http://www.prestashop.com for more information.
 *
 *  @author    PrestaShop SA <contact@prestashop.com>
 *  @copyright 2007-2016 PrestaShop SA
 *  @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *  International Registered Trademark & Property of PrestaShop SA
 */
use PrestaShop\Module\AutoUpgrade\Tools14;
use PrestaShop\Module\AutoUpgrade\UpgradeTools\TaskRepository;

/**
 * This file is the entrypoint for all ajax requests during a upgrade, rollback or configuration.
 * In order to get the admin context, this file is copied to the admin/autoupgrade folder of your shop when the module configuration is reached.
 *
 * Calling it from the module/autoupgrade folder will have unwanted consequences on the upgrade and your shop.
 */
require_once realpath(dirname(__FILE__).'/../../modules/autoupgrade').'/ajax-upgradetabconfig.php';
$container = autoupgrade_init_container(dirname(__FILE__));

(new \PrestaShop\Module\AutoUpgrade\ErrorHandler($container->getLogger()))->enable();

if (!$container->getCookie()->check($_COOKIE)) {
    // If this is an XSS attempt, then we should only display a simple, secure page
    if (ob_get_level() && ob_get_length() > 0) {
        ob_clean();
    }
    echo '{wrong token}';
    die(1);
}

$controller = TaskRepository::get(Tools14::getValue('action'), $container);
$controller->init();
$controller->run();
echo $controller->getJsonResponse();

**Comment by V41F** [comment]
@Quetzacoalt91 any information what is wrong in my ajax-upgradetab.php? thx a lot.

**Comment by Quetzacoalt91** [comment]
Sorry, there is a misunderstanding, I didn't expect the file content.

I wanted you to make an upgrade and use the console browser:

![snimek obrazovky 2018-09-11 v 21 43 44](https://user-images.githubusercontent.com/41673053/45386483-bd380880-b613-11e8-8df4-6e79e99bc0b1.png)

When you click on the line with the file `ajax-upgradetab.php` and the code 500 on the left, you should have the details of this call. What I expect from you is to click on the response tab, and copy paste the response returned by the server.

**Comment by V41F** [comment]
@Quetzacoalt91 here is the result:

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at 
 [no address given] to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
<hr>
<address>Apache/2.4.33 (Ubuntu) Server at tvojefarma.cz Port 443</address>
</body></html>

**Comment by Quetzacoalt91** [comment]
Thank you @wewew85.

I hoped seeing more details than the generic default message of Apache, but it appears I was wrong.
Unfortunately, this does not provide us any information to go further on the debug. Can you please ask your hosting provider to get the apache / PHP logs? This is our last find details on what's happening.

Regards

**Comment by V41F** [comment]
Hello @Quetzacoalt91 
here is the result from my hosting provider: (file removed)

**Comment by Quetzacoalt91** [comment]
Okay, now we got something!

```
[Wed Sep 19 20:53:02.850339 2018] [core:alert] [pid 31685] [client 89.102.10.93:54852] /var/www/hosting/tvojefarma.cz/xxxx/.htaccess: Option MultiViews not allowed here, referer: https://tvojefarma.cz/xxxx/index.php?tab=AdminSelfUpgrade&token=4e4368600cda7bcd6696b4b6ae6ec388
[Wed Sep 19 20:53:37.261370 2018] [core:alert] [pid 31980] [client 89.102.10.93:54880] /var/www/hosting/tvojefarma.cz/xxxx/.htaccess: Option MultiViews not allowed here, referer: https://tvojefarma.cz/xxxx/index.php?tab=AdminSelfUpgrade&token=4e4368600cda7bcd6696b4b6ae6ec388
[Wed Sep 19 21:04:23.553185 2018] [core:alert] [pid 32384] [client 89.102.10.93:55060] /var/www/hosting/tvojefarma.cz/xxxx/.htaccess: Option MultiViews not allowed here, referer: https://tvojefarma.cz/xxxx/index.php?tab=AdminSelfUpgrade&token=4e4368600cda7bcd6696b4b6ae6ec388
```

We're working on the release of PrestaShop 1.7.5, so I can't work on this issue today, but I'm glad we finally found what's wrong in your case. :)

**Comment by V41F** [comment]
Hello @Quetzacoalt91 
any new information?
thx

**Comment by V41F** [comment]
Hello @Quetzacoalt91 ,
I tried to upgrade again but with the same result:-( Could you pls help me?
thx

**Comment by Quetzacoalt91** [comment]
Hi @wewew85 ,

This topic on the forum could help you: https://www.prestashop.com/forums/topic/567307-option-multiviews-not-allowed-here-on-prestashop-17/

**Comment by V41F** [comment]
Hi @Quetzacoalt91 ,
thx for your response, but I have no idea what to do. Could you pls explain me how to do it?
thank you so much.

**Comment by Quetzacoalt91** [comment]
Do not hesitate to be helped by somebody you know able to modify Apache hosts.

Basically, you have to modify the Apache configuration on your server.
This line is missing in the configuration:
```
    AllowOverride Indexes Options=All,MultiViews
```

and prevents the BO to work properly with the autoupgrade.

**Comment by V41F** [comment]
Hi @Quetzacoalt91 , 
so I asked my webhosting support to set up Apache and here is the result:

After set up, webpage is not available. Here is the log:
/var/www/hosting/tvojefarma.cz/.htaccess:
SetEnv not allowed here

Could you pls help me? What is wrong?
thx a lot.

**Comment by V41F** [comment]
Hi @Quetzacoalt91 ,
any new idea pls?

**Comment by Quetzacoalt91** [comment]
Hi @wewew85,

Do not hesitate to search on Internet when you have the actual error displayed, you can find the solution. :)
I tried to reproduce the error, and found out the following config may help you:

```
AllowOverride FileInfo AuthConfig Indexes Options=All,MultiViews
```

The solution is based on https://stackoverflow.com/questions/17239759/apache-setenv-not-allowed-here-in-apache-logs. Sorry for the previous example which wasn't accurate enough.

**Comment by Quetzacoalt91** [comment]
By the way, having

```
                AllowOverride All
```

would fix all the similar issues, but I know exactly what it could imply in a security point of view.

**Comment by V41F** [comment]
Hi @Quetzacoalt91 ,
thx for you answer.
so this is the answer for my webhosting support? Or I have to set up? and where?

**Comment by Quetzacoalt91** [comment]
It seems safer to ask your webhosting support to do it for you if you don't know how to / cannot do it by yourself.

**Comment by Quetzacoalt91** [comment]
Now your css and js files are in HTTP 500? What's the error this time in the logs?

**Comment by V41F** [comment]
Hi @Quetzacoalt91 ,
I sent your explanation to my webhosting support. They set up Apache server as you wrote:
AllowOverride FileInfo AuthConfig Indexes Options=All,MultiViews

Then css was completely destroyed (I sent you image in attachment). So they rollback. It means that I have no error in log because there was no error only destroyed css.

**Comment by efernandesng** [comment]
@wewew85 Check if you have the `vendor/autoload.php` file on `modules/autoupgrade/`. I resolver similar problem running `composer install` on `modules/autoupgrade/`.
Before I got the follow error
```
[error] 21946#0: *262716 FastCGI sent in stderr: "PHP message: PHP Warning:  require_once(/usr/share/nginx/xxxx/modules/autoupgrade/vendor/autoload.php): failed to open stream: No such file or directory in /usr/share/nginx/xxxx/modules/autoupgrade/AdminSelfUpgrade.php on line 38
```

**Comment by V41F** [comment]
@efernandesng @Quetzacoalt91 
I did it. Now everything is down. Front show error 500. Back office I can not load. pls help me. I deleted all files from FTP and upload my backup and nothing change:-(((((

**Comment by Quetzacoalt91** [comment]
You should enable the dev mode to have more details on the actual issue. :)

**Comment by wewew85** [comment]
@Quetzacoalt91 ,
here you have it. I had to upload my backup database because the database was broken by upgrade prestashop. How is it possible?
![image](https://user-images.githubusercontent.com/41673053/48477132-103f5f00-e801-11e8-9e3d-a296875019c5.png)


I tried to update my prestashop many times but without any success. Here is the error log from the last update:

_Error while copying file /adminXXXX/.htaccess
Error when trying to upgrade file /adminXXXX/.htaccess.
[INTERNAL] /var/www/hosting/tvojefarma.cz/config/config.inc.php line 121 - Error: Call to a member function getName() on null #0 /var/www/hosting/tvojefarma.cz/modules/autoupgrade/classes/UpgradeContainer.php(475): require_once() #1 /var/www/hosting/tvojefarma.cz/modules/autoupgrade/classes/TaskRunner/AbstractTask.php(120): PrestaShop\Module\AutoUpgrade\UpgradeContainer->initPrestaShopCore() #2 /var/www/hosting/tvojefarma.cz/admin2311/autoupgrade/ajax-upgradetab.php(51): PrestaShop\Module\AutoUpgrade\TaskRunner\AbstractTask->init() #3 {main}_

**Comment by V41F** [comment]
Hi @Quetzacoalt91 ,
I'm still waiting for new information to upgrade my PS 1.7.3.0 to latest version. 
thx a lot.

**Comment by Quetzacoalt91** [comment]
Sorry about that @wewew85,

Thanks for the stack trace of the final error. But I guess this is a consequence from another issue which could be found in the log.txt file, hidden among the upgrade details. Can you please have a look at the whole file? Thanks

**Comment by V41F** [comment]
Hi @Quetzacoalt91,
sorry I have been on holiday. Here is the error log file.
Lukas
[log.txt](https://github.com/PrestaShop/autoupgrade/files/2730638/log.txt)

**Comment by V41F** [comment]
Hi @Quetzacoalt91 ,
I tried to update on 1.7.5. the result is still the same. Did you find something in log file? 
thx a lot.
Lukas

**Comment by kielerrr** [comment]
The Modsec problem

Disabling Modsec during the one click update fixed the issue for me.

I tried everything posted on the forums but still kept getting the error. Once modsec was turned off, my 1.7.3 -> 1.7.5 One Click Upgrade worked flawlessly.

This should be considered as a requirement in the preflight check to save a lot of headache.

The caching problem

I was also having trouble disabling caching. I would disable caching, reload and it would be enabled again. I thought I had memcached installed because the radio button in performance, although greyed out, was checked. Turns out, I had memcached installed a service and not as a pecl extension. When running phpinfo(); memcached did not appear (meaning it wasn't hooked up as a module)

If you're having trouble with caching, make sure to install pecl. Install libmemcached first, then memcached. If you're running different versions of PHP, you have to install it with the pecl binary linked to that version.

IE
/usr/bin/ea-php72-pecl install memcached
/usr/bin/ea-php73-pecl install memcached


After going through a number of tutorials, [this ](https://serverpilot.io/docs/how-to-install-the-php-memcache-extension) one finally helped me get memcached installed as a PHP module.

Hope this helps someone!
