### ISSUE TITLE
Module upgrade fails because of composer class not found

### ISSUE THREAD

**Issue by Quetzacoalt91** [PrestaShop/autoupgrade#175]
**Describe the bug**
Seen on [build.prestashop.com](https://build.prestashop.com/news/prestashop-1-7-4-3-1-6-1-21-maintenance-releases/#comment-4128761271)

**Upgrade environment (please complete the following information):**
 - Version you started from: 1.7.4.2
 - Version you upgrade to: 1.7.4.3
 - Way of upgrade: Web
 - Step concerned: upgradeModules

**Displayed log**

```
[2018-10-04 16:52:00] [INTERNAL] .... \modules\dashproducts\vendor\composer\autoload_real.php line 30 - Error: Class 'Composer\Autoload\ComposerStaticInit991e418cf6afca38df754c22bb61fefe' not found
#0 .....\modules\dashproducts\vendor\autoload.php(7): ComposerAutoloaderInit991e418cf6afca38df754c22bb61fefe::getLoader()
#1 C:\.....\app\AppKernel.php(220): include_once('C:\\wwwroot\\Ensh...')
#2 C:\......\app\AppKernel.php(69): AppKernel->enableComposerAutoloaderOnModules(Array)
#3 C:\......\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Kernel.php(492): AppKernel->registerBundles()
#4 C:\........\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Kernel.php(132): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#5 C:\.......\modules\autoupgrade\classes\UpgradeTools\ModuleAdapter.php(74): Symfony\Component\HttpKernel\Kernel->boot()
#6 C:\..........\modules\autoupgrade\classes\UpgradeTools\ModuleAdapter.php(190): PrestaShop\Module\AutoUpgrade\UpgradeTools\ModuleAdapter->getModuleDataUpdater()
#7 C:\..........\modules\autoupgrade\classes\TaskRunner\Upgrade\UpgradeModules.php(65): PrestaShop\Module\AutoUpgrade\UpgradeTools\ModuleAdapter->upgradeModule(7429, 'gamification')
#8 C:\.\admin\autoupgrade\...........ajax-upgradetab.php(52): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeModules->run()
#9 {main}
```

**Server (please complete the following information):**
 - Module Version 4.3.0

**Comment by Quetzacoalt91** [comment]
Should be fixed on v4.8.0 with #306
