### ISSUE TITLE
Fatal error following #176

### ISSUE THREAD

**Issue by Quetzacoalt91** [PrestaShop/autoupgrade#178]
**Describe the bug**
A fatal error appears when the `dev` branch is used. cc @eternoendless 

**Upgrade environment (please complete the following information):**
 - Version you started from: 1.6.0.11
 - Version you upgrade to: N/A
 - Way of upgrade: Web
 - Step concerned: Configuration step 

**Displayed log**

```
Fatal error: Uncaught exception 'Twig_Error_Syntax' with message 'Unknown "trans_default_domain" tag.' in /var/www/html/modules/autoupgrade/views/templates/block/checklist.twig:1 
Stack trace: 
#0 /var/www/html/modules/autoupgrade/vendor/twig/twig/lib/Twig/Parser.php(105): Twig_Parser->subparse(NULL, false) 
#1 /var/www/html/modules/autoupgrade/vendor/twig/twig/lib/Twig/Environment.php(716): Twig_Parser->parse(Object(Twig_TokenStream)) 
#2 /var/www/html/modules/autoupgrade/vendor/twig/twig/lib/Twig/Environment.php(774): Twig_Environment->parse(Object(Twig_TokenStream)) 
#3 /var/www/html/modules/autoupgrade/vendor/twig/twig/lib/Twig/Environment.php(452): Twig_Environment->compileSource(Object(Twig_Source)) 
#4 /var/www/html/modules/autoupgrade/vendor/twig/twig/lib/Twig/Environment.php(363): Twig_Environment->loadTemplate('@ModuleAutoUpgr...') 
#5 /var/www/html/modules/autoupgrade/classes/Twig/Block/UpgradeChecklist.php(132): Twig_Environment->render('@ModuleAutoUpgr...', Array) 
#6 /var/www/html/modules/autoupgrade/classes/Upgrade in /var/www/html/modules/autoupgrade/views/templates/block/checklist.twig on line 1
```

**Server (please complete the following information):**
 - Web Server: Apache
 - PHP Version: 5.6
 - Module Version: dev, 4.4.0

**Comment by Quetzacoalt91** [comment]
Fixed by #181
