### ISSUE TITLE
Error: Class 'Core_Business_ContainerBuilder' not found (PS: 1.6.24 to 1.7.2)

### ISSUE THREAD

**Issue by carras** [PrestaShop/autoupgrade#324]
Hello there:

After try many times to use the autougrade module (v4.8) to upgrade PS 1.6.24 to 1.7.2; I always get the following errors:

Does anybody know what's wrong? Thanks.

[INTERNAL] 
/home//public_html/config/bootstrap.php line 27 - Error: Class 'Core_Business_ContainerBuilder' not found 

#0 /home//public_html/config/config.inc.php(66): require_once() 
#1 /home//public_html/modules/autoupgrade/classes/UpgradeContainer.php(499): require_once('/home//p...') 
#2 /home//public_html/modules/autoupgrade/classes/TaskRunner/AbstractTask.php(120): PrestaShop\Module\AutoUpgrade\UpgradeContainer->initPrestaShopCore() 
#3 /home//public_html/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(75): PrestaShop\Module\AutoUpgrade\TaskRunner\AbstractTask->init() 
#4 /home//public_html/controlador/autoupgrade/ajax-upgradetab.php(52): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->init() 
#5 {main}

**Comment by carras** [comment]
Trying with autoupgrade v4.9 didn't work either.
